-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cw_wikis (
  wiki_dbname VARCHAR(64) NOT NULL,
  wiki_sitename VARCHAR(128) NOT NULL,
  wiki_language VARCHAR(12) NOT NULL,
  wiki_private SMALLINT DEFAULT 0 NOT NULL,
  wiki_creation BLOB NOT NULL,
  wiki_url CLOB DEFAULT NULL,
  wiki_closed SMALLINT DEFAULT 0 NOT NULL,
  wiki_closed_timestamp BLOB DEFAULT NULL,
  wiki_inactive SMALLINT DEFAULT 0 NOT NULL,
  wiki_inactive_timestamp BLOB DEFAULT NULL,
  wiki_inactive_exempt SMALLINT DEFAULT 0 NOT NULL,
  wiki_inactive_exempt_reason CLOB DEFAULT NULL,
  wiki_deleted SMALLINT DEFAULT 0 NOT NULL,
  wiki_deleted_timestamp BLOB DEFAULT NULL,
  wiki_locked SMALLINT DEFAULT 0 NOT NULL,
  wiki_nsfw SMALLINT DEFAULT 0 NOT NULL,
  wiki_dbcluster VARCHAR(5) DEFAULT NULL,
  wiki_category VARCHAR(64) NOT NULL,
  wiki_experimental SMALLINT DEFAULT 0 NOT NULL,
  wiki_extra CLOB DEFAULT NULL,
  PRIMARY KEY(wiki_dbname)
);

CREATE INDEX wiki_dbname ON /*_*/cw_wikis (wiki_dbname);

CREATE INDEX wiki_dbcluster ON /*_*/cw_wikis (wiki_dbcluster);


CREATE TABLE /*_*/cw_requests (
  cw_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cw_comment CLOB DEFAULT NULL,
  cw_dbname VARCHAR(64) NOT NULL,
  cw_language VARCHAR(12) NOT NULL,
  cw_private SMALLINT DEFAULT 0 NOT NULL,
  cw_sitename VARCHAR(128) NOT NULL,
  cw_status VARCHAR(16) DEFAULT NULL,
  cw_timestamp BLOB NOT NULL,
  cw_url VARCHAR(96) NOT NULL,
  cw_user BIGINT UNSIGNED NOT NULL,
  cw_category VARCHAR(64) NOT NULL,
  cw_visibility SMALLINT DEFAULT 0 NOT NULL,
  cw_locked SMALLINT DEFAULT 0 NOT NULL,
  cw_nsfw SMALLINT DEFAULT 0 NOT NULL,
  cw_bio SMALLINT DEFAULT 0 NOT NULL,
  cw_extra CLOB DEFAULT NULL
);

CREATE INDEX cw_status ON /*_*/cw_requests (cw_status);

CREATE INDEX cw_timestamp ON /*_*/cw_requests (cw_timestamp);


CREATE TABLE /*_*/cw_comments (
  cw_id BIGINT UNSIGNED NOT NULL, cw_comment BLOB NOT NULL,
  cw_comment_timestamp BLOB NOT NULL,
  cw_comment_user BIGINT UNSIGNED NOT NULL
);


CREATE TABLE /*_*/cw_history (
  cw_history_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cw_id BIGINT UNSIGNED NOT NULL,
  cw_history_action VARCHAR(50) NOT NULL,
  cw_history_actor BIGINT UNSIGNED NOT NULL,
  cw_history_details BLOB NOT NULL,
  cw_history_timestamp BLOB NOT NULL
);
