-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cw_wikis (
  wiki_dbname VARCHAR(64) NOT NULL,
  wiki_sitename VARCHAR(128) NOT NULL,
  wiki_language VARCHAR(12) NOT NULL,
  wiki_private TINYINT DEFAULT 0 NOT NULL,
  wiki_creation BINARY(14) NOT NULL,
  wiki_url LONGTEXT DEFAULT NULL,
  wiki_closed TINYINT DEFAULT 0 NOT NULL,
  wiki_closed_timestamp BINARY(14) DEFAULT NULL,
  wiki_inactive TINYINT DEFAULT 0 NOT NULL,
  wiki_inactive_timestamp BINARY(14) DEFAULT NULL,
  wiki_inactive_exempt TINYINT DEFAULT 0 NOT NULL,
  wiki_inactive_exempt_reason LONGTEXT DEFAULT NULL,
  wiki_deleted TINYINT DEFAULT 0 NOT NULL,
  wiki_deleted_timestamp BINARY(14) DEFAULT NULL,
  wiki_locked TINYINT DEFAULT 0 NOT NULL,
  wiki_nsfw TINYINT DEFAULT 0 NOT NULL,
  wiki_dbcluster VARCHAR(5) DEFAULT NULL,
  wiki_category VARCHAR(64) NOT NULL,
  wiki_experimental TINYINT DEFAULT 0 NOT NULL,
  wiki_extra JSON DEFAULT NULL,
  INDEX wiki_dbname (wiki_dbname),
  INDEX wiki_dbcluster (wiki_dbcluster),
  PRIMARY KEY(wiki_dbname)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cw_requests (
  cw_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cw_comment LONGTEXT DEFAULT NULL,
  cw_dbname VARCHAR(64) NOT NULL,
  cw_language VARCHAR(12) NOT NULL,
  cw_private TINYINT DEFAULT 0 NOT NULL,
  cw_sitename VARCHAR(128) NOT NULL,
  cw_status VARCHAR(16) DEFAULT NULL,
  cw_timestamp BINARY(14) NOT NULL,
  cw_url VARCHAR(96) NOT NULL,
  cw_user BIGINT UNSIGNED NOT NULL,
  cw_category VARCHAR(64) NOT NULL,
  cw_visibility TINYINT DEFAULT 0 NOT NULL,
  cw_locked TINYINT DEFAULT 0 NOT NULL,
  cw_nsfw TINYINT DEFAULT 0 NOT NULL,
  cw_bio TINYINT DEFAULT 0 NOT NULL,
  cw_extra JSON DEFAULT NULL,
  INDEX cw_status (cw_status),
  INDEX cw_timestamp (cw_timestamp),
  PRIMARY KEY(cw_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cw_comments (
  cw_id BIGINT UNSIGNED NOT NULL,
  cw_comment LONGBLOB NOT NULL,
  cw_comment_timestamp BINARY(14) NOT NULL,
  cw_comment_user BIGINT UNSIGNED NOT NULL
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cw_history (
  cw_history_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cw_id BIGINT UNSIGNED NOT NULL,
  cw_history_action VARCHAR(50) NOT NULL,
  cw_history_actor BIGINT UNSIGNED NOT NULL,
  cw_history_details LONGBLOB NOT NULL,
  cw_history_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(cw_history_id)
) /*$wgDBTableOptions*/;
